---

- name: Converge default
  hosts: all

  vars:
    group_list:
      - name: group2
        gid: 1991

    user_list:
      - name: hjanmaat
        comment: Hein Janmaat
      - name: user3
        non_unique: true
        uid: 33
        password: >-
          $6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1
      - name: user4
        generate_ssh_key: true
      - name: system_user1
        system: true
      - name: foo
        state: absent
        remove: true
      - name: user6
        authorized_keys_exclusive: true
        authorized_keys:
          # yamllint disable-line rule:line-length
          - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGDKKpFlYiNPE7yo/sxcfyTw7Lah5BV2RCvyj2xrkNkUIhbIcLJTaSrawuF/+5wR/qcs3SmEU+5OvdvUohWPQCmaDOWz5RDGiAy1HVh9msim5zeMARkfloBoDyclqmjsULSyEeBeuiiNMfjxacd/2XjPZ7Th7uiyxoguI5F6EWXpsDu4dAAZITjPMXoktG5Zf2no7L/y0+Z49xwoTE59+kJ1gL5XYt8uLMTI53LUL0fcOGoNttG15adj46XriHsB/RsMjetb7br/q1DJnDuIxE7E/Gp/89ZMM0ugkNXx8AzZTmXT25QQ2GvhzMB6TMor12S0BMoQP/lObYx3/VzuxZ key1'  # noqa 204
          - "{{ lookup('file', 'key2.pub') }}"
      - name: user7
        authorized_keys:
          - "{{ lookup('file', 'key2.pub') }}"

  roles:
    - role: flokoe.users

- name: Converge default (with special vars)
  hosts: all

  vars:
    use_global_users_group: true
    keep_existing_groups: true
    user_list:
      - name: user1
        uid: 1337
      - name: user2
        groups:
          - group2
      - name: user5
        home_mode: '700'
        home_owner: root
        home_group: root

  roles:
    - role: flokoe.users
