---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint --strict .
  ansible-lint

platforms:
  - name: ubuntu-bionic
    hostname: instance
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true

  - name: ubuntu-focal
    hostname: instance
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml

verifier:
  name: ansible
